### ISSUE TITLE
Couldn't parse data file minecraft:repair_item

### ISSUE THREAD

**Issue by TwinTNR** [Joshcraft2002/joshs-more-foods#42]
Help, i'm on paper 1.21 and got this error message.

```
Couldn't parse data file minecraft:repair_item from minecraft:recipe/repair_item.json
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
        at net.minecraft.util.GsonHelper.fromNullableJson(GsonHelper.java:432) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.GsonHelper.fromJson(GsonHelper.java:437) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.util.GsonHelper.fromJson(GsonHelper.java:489) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.scanDirectory(SimpleJsonResourceReloadListener.java:43) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.prepare(SimpleJsonResourceReloadListener.java:31) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.item.crafting.RecipeManager.prepare(RecipeManager.java:42) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.packs.resources.SimplePreparableReloadListener.lambda$reload$0(SimplePreparableReloadListener.java:17) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.io.EOFException: End of input at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1457) ~[gson-2.10.1.jar:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:558) ~[gson-2.10.1.jar:?]
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:769) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.1.jar:?]
        at net.minecraft.util.GsonHelper.fromNullableJson(GsonHelper.java:430) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        ... 10 more
```

**Comment by Joshcraft2002** [comment]
This doesn't look like it's from my pack, do you have any other datapacks or plugins installed that might be the cause?

**Comment by TwinTNR** [comment]
Yeah i have other datapacks, i'll check it one by one, thanks.
