### ISSUE TITLE
No recipes work

### ISSUE THREAD

**Issue by Dragsio** [Joshcraft2002/joshs-more-foods#46]
Hi,

None of the recipes of this datapack work for me in version [5.2.0-pre1](https://modrinth.com/datapack/joshs-more-foods/version/5.2.0-pre1).
I am using Purpur 1.21.1 server.

**When starting the server I get errors like this (for each item):**
```log
[03:03:22] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:rice - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:rice"}
```

or

```log
[03:03:23] [ServerMain/ERROR]: Parsing error loading recipe jmmf:bread/potato_bread
com.google.gson.JsonParseException: No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:bread/potato_bread"}; Map entry 'W' : Failed to parse either. First: Not a json array: "minecraft:wheat"; Second: Not a JSON object: "minecraft:wheat"; Not a JSON object: "minecraft:wheat"
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
	at net.minecraft.world.item.crafting.RecipeManager.apply(RecipeManager.java:68) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
	at net.minecraft.world.item.crafting.RecipeManager.apply(RecipeManager.java:42) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.lambda$reload$1(SimplePreparableReloadListener.java:19) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.lambda$new$3(SimpleReloadInstance.java:90) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
	at net.minecraft.Util.blockUntilDone(Util.java:898) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
	at net.minecraft.Util.blockUntilDone(Util.java:887) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
	at net.minecraft.server.Main.main(Main.java:277) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
	at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
	at org.bukkit.craftbukkit.Main.main(Main.java:295) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Joshcraft2002** [comment]
please choose a version for 1.21.1 (5.1.5)

5.2.0-pre1 is for minecraft version 1.21.2-pre1 and above
