### ISSUE TITLE
Error installing datapack on server

### ISSUE THREAD

**Issue by MOIX346** [Joshcraft2002/joshs-more-foods#47]
![image](https://github.com/user-attachments/assets/3da5c0ee-5664-4a19-9276-6152decb4146)
![image](https://github.com/user-attachments/assets/96419954-41a8-4a46-a586-c326c89904c2)
[11:49:20] [ServerMain/INFO]: Found new data pack file/joshs-more-foods_5.2.0-pre1_data_pack.zip, loading it automatically
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:rice - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:rice"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:tea/dandelion_tea - No component with type: 'minecraft:consumable'; No component with type: 'minecraft:consumable'; No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:tea/dandelion_tea","minecraft:consumable":{"sound":"minecraft:entity.generic.drink","has_consume_particles":false,"on_consume_effects":[{"type":"apply_effects","effects":[{"id":"minecraft:regeneration","duration":200}]}]}}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:tea/sweet_berry_tea - No component with type: 'minecraft:consumable'; No component with type: 'minecraft:consumable'; No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:tea/sweet_berry_tea","minecraft:consumable":{"sound":"minecraft:entity.generic.drink","has_consume_particles":false,"on_consume_effects":[{"type":"apply_effects","effects":[{"id":"minecraft:regeneration","duration":200}]}]}}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:red_rice_bowl - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:red_rice_bowl"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:red_rice - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:red_rice"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:black_tea_leaves - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:black_tea_leaves"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:tea/rose_tea - No component with type: 'minecraft:consumable'; No component with type: 'minecraft:consumable'; No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:tea/rose_tea","minecraft:consumable":{"sound":"minecraft:entity.generic.drink","has_consume_particles":false,"on_consume_effects":[{"type":"apply_effects","effects":[{"id":"minecraft:regeneration","duration":200}]}]}}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:pie/steak_pie - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:pie/steak_pie"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:tea/green_tea - No component with type: 'minecraft:consumable'; No component with type: 'minecraft:consumable'; No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:tea/green_tea","minecraft:consumable":{"sound":"minecraft:entity.generic.drink","has_consume_particles":false,"on_consume_effects":[{"type":"apply_effects","effects":[{"id":"minecraft:regeneration","duration":200}]}]}}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:fried_rice - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:rice_meal/fried_rice"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:tea/birch_tea - No component with type: 'minecraft:consumable'; No component with type: 'minecraft:consumable'; No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:tea/birch_tea","minecraft:consumable":{"sound":"minecraft:entity.generic.drink","has_consume_particles":false,"on_consume_effects":[{"type":"apply_effects","effects":[{"id":"minecraft:regeneration","duration":200}]}]}}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:egg_drop_soup - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:soup/egg_drop_soup"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:pie/chicken_pot_pie - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:pie/chicken_pot_pie"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:fried_egg - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:fried_egg"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:tea/sakura_tea - No component with type: 'minecraft:consumable'; No component with type: 'minecraft:consumable'; No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:tea/sakura_tea","minecraft:consumable":{"sound":"minecraft:entity.generic.drink","has_consume_particles":false,"on_consume_effects":[{"type":"apply_effects","effects":[{"id":"minecraft:regeneration","duration":200}]}]}}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:boiled_egg - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:boiled_egg"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:pie/pork_pie - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:pie/pork_pie"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:rice_bowl - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:rice_bowl"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:tea/spruce_tea - No component with type: 'minecraft:consumable'; No component with type: 'minecraft:consumable'; No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:tea/spruce_tea","minecraft:consumable":{"sound":"minecraft:entity.generic.drink","has_consume_particles":false,"on_consume_effects":[{"type":"apply_effects","effects":[{"id":"minecraft:regeneration","duration":200}]}]}}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:tea/sunflower_tea - No component with type: 'minecraft:consumable'; No component with type: 'minecraft:consumable'; No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:tea/sunflower_tea","minecraft:consumable":{"sound":"minecraft:entity.generic.drink","has_consume_particles":false,"on_consume_effects":[{"type":"apply_effects","effects":[{"id":"minecraft:regeneration","duration":200}]}]}}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:rotten_stew - No component with type: 'minecraft:use_remainder'; No component with type: 'minecraft:use_remainder'; No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:soup/rotten_stew","minecraft:use_remainder":{"id":"minecraft:bowl"}}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:tea/bamboo_tea - No component with type: 'minecraft:use_remainder'; No component with type: 'minecraft:use_remainder'; No component with type: 'minecraft:consumable'; No component with type: 'minecraft:consumable'; No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:tea/bamboo_tea","minecraft:consumable":{"sound":"minecraft:entity.generic.drink","has_consume_particles":false,"on_consume_effects":[{"type":"apply_effects","effects":[{"id":"minecraft:regeneration","duration":200}]}]},"minecraft:use_remainder":{"id":"minecraft:structure_block","components":{"minecraft:item_name":"{ 'translate': 'item.jmmf.teacup', 'italic': false }","minecraft:rarity":"common","minecraft:item_model":"jmmf:teacup","minecraft:custom_data":{"smithed":{"id":"jmmf:teacup"}}}}}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:tea/cornflower_tea - No component with type: 'minecraft:consumable'; No component with type: 'minecraft:consumable'; No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:tea/cornflower_tea","minecraft:consumable":{"sound":"minecraft:entity.generic.drink","has_consume_particles":false,"on_consume_effects":[{"type":"apply_effects","effects":[{"id":"minecraft:regeneration","duration":200}]}]}}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:bone_broth - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:soup/bone_broth"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:tea/black_tea - No component with type: 'minecraft:consumable'; No component with type: 'minecraft:consumable'; No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:tea/black_tea","minecraft:consumable":{"sound":"minecraft:entity.generic.drink","has_consume_particles":false,"on_consume_effects":[{"type":"apply_effects","effects":[{"id":"minecraft:regeneration","amplifier":1,"duration":100}]}]}}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:tea/chamomile_tea - No component with type: 'minecraft:consumable'; No component with type: 'minecraft:consumable'; No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:tea/chamomile_tea","minecraft:consumable":{"sound":"minecraft:entity.generic.drink","has_consume_particles":false,"on_consume_effects":[{"type":"apply_effects","effects":[{"id":"minecraft:regeneration","duration":200}]}]}}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:champorado - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:rice_meal/champorado"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:nutritionbook - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:nutritionbook"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:cookbook - No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:cookbook"}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse element minecraft:item_modifier/jmmf:tea/beetroot_tea - No component with type: 'minecraft:consumable'; No component with type: 'minecraft:consumable'; No component with type: 'minecraft:item_model'; No component with type: 'minecraft:item_model' missed input: {"minecraft:item_model":"jmmf:tea/beetroot_tea","minecraft:consumable":{"sound":"minecraft:entity.generic.drink","has_consume_particles":false,"on_consume_effects":[{"type":"apply_effects","effects":[{"id":"minecraft:regeneration","duration":200}]}]}}
[11:49:21] [Worker-Main-1/ERROR]: Couldn't parse data file valiance:item/grinderizor from valiance:loot_table/item/grinderizor.json
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2 path $
	at net.minecraft.util.GsonHelper.fromNullableJson(GsonHelper.java:432) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
	at net.minecraft.util.GsonHelper.fromJson(GsonHelper.java:437) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
	at net.minecraft.util.GsonHelper.fromJson(GsonHelper.java:489) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.scanDirectory(SimpleJsonResourceReloadListener.java:43) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
	at net.minecraft.server.ReloadableServerRegistries.lambda$scheduleElementParse$4(ReloadableServerRegistries.java:67) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1447) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:558) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:769) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.1.jar:?]
	at net.minecraft.util.GsonHelper.fromNullableJson(GsonHelper.java:430) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
	... 8 more

**Comment by MOIX346** [comment]
I'm layman in this. Please help someone!

**Comment by Joshcraft2002** [comment]
which minecraft version are you on? the datapack version you have is 5.2.0-pre1 which is for 1.21.2-rc1 and above

**Comment by Joshcraft2002** [comment]
that solution should work, closing this old(?) thread
